using System.Text;
using UnityEngine;

namespace BaseSkinSwapperBuilder
{
    public class BaseSkinSwapperTemplate
    {
        private readonly BaseSkinSwapperInfo info;

        public BaseSkinSwapperTemplate(BaseSkinSwapperInfo BaseSkinSwapperInfo)
        {
            info = BaseSkinSwapperInfo;
        }

        public string TransformText()
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Generated by BaseSkinSwapperBuilder. Re-running Build overwrites this file.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using RoR2;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UnityEngine.AddressableAssets;");
            sb.AppendLine("using static RoR2.SerializableLoadout.BodyLoadout;");
            sb.AppendLine("using static RoR2.SerializableLoadout;");
            sb.AppendLine();
            sb.Append("namespace ").Append(info.assetInfo.uccModName).AppendLine();
            sb.AppendLine("{");
            sb.Append("  public partial class ").Append(info.assetInfo.uccModName).AppendLine("Plugin");
            sb.AppendLine("  {");
            sb.Append("    static ").Append(info.Name).Append("Extension _").Append(info.Name).Append("Extension = new ").Append(info.Name).Append("Extension();");
            sb.AppendLine(" ");
            sb.Append("    public class ").Append(info.Name).AppendLine("Extension");
            sb.AppendLine("    {");
            sb.AppendLine("      internal void BeforeStart() { }");
            sb.AppendLine();
            sb.AppendLine("      internal void AfterStart() { }");
            sb.AppendLine();
            sb.AppendLine("      internal void BeforeBodyCatalogInit() { }");
            sb.AppendLine();
            sb.AppendLine("      internal void AfterBodyCatalogInit() { }");
            sb.AppendLine();
            sb.AppendLine("    }");
            
            // SkinAddedAdjustment constructor
            sb.Append("  static ").Append(info.assetInfo.uccModName).AppendLine("Plugin()");
            sb.AppendLine("  {");
            foreach (var skin in info._SkinList)
            {
                string skinName = SanitizeIdentifier(skin.skinDef.name);
                string bodyPrefix = SanitizeIdentifier(skin.skinDef.bodyName);
                sb.Append($"    {bodyPrefix}{skinName}SkinAddedEvent +=").Append($" On{bodyPrefix}{skinName}SkinAdded").AppendLine(";");
            }
            sb.AppendLine("  }");

            foreach (var fix in info._SkinList)
            {
                Write_Skin(sb, fix);
            }

            sb.AppendLine("  }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private void Write_Skin(StringBuilder sb, BaseSkinSwapperInfo._Skin fix)
        {
            string skinName = SanitizeIdentifier(fix.skinDef.name);
            string bodyPrefix = SanitizeIdentifier(fix.skinDef.bodyName);
            string methodName = $"On{bodyPrefix}{skinName}SkinAdded";

            sb.Append("    private static void ").Append(methodName).AppendLine("(object sender, SkinAddedArgs e)");
            sb.AppendLine("    {");
            sb.Append("     CharacterSpawnCard obj = Addressables.LoadAssetAsync<CharacterSpawnCard>((object)\"").Append(fix.CharacterSpawnCardPath).AppendLine("\").WaitForCompletion();");
            sb.AppendLine("     SerializableLoadout val = new SerializableLoadout();");
            sb.AppendLine("     val.bodyLoadouts = new BodyLoadout[] {");
            sb.AppendLine("   new BodyLoadout");
            sb.AppendLine("   {");
            sb.AppendLine("      body = e.bodyPrefab.GetComponent<CharacterBody>(),");
            sb.AppendLine("      skinChoice = e.skinDef,");
            sb.AppendLine("      skillChoices = new SkillChoice[0]");
            sb.AppendLine("  }");
            sb.AppendLine("};");
            sb.AppendLine("obj.loadout = val;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        public static string SanitizeIdentifier(string input)
        {
            if (string.IsNullOrWhiteSpace(input))
                return "Unknown";

            var sb = new StringBuilder();
            bool capitalizeNext = true;

            foreach (char c in input)
            {
                if (char.IsLetterOrDigit(c))
                {
                    sb.Append(capitalizeNext ? char.ToUpper(c) : c);
                    capitalizeNext = false;
                }
                else
                {
                    capitalizeNext = true;
                }
            }

            string result = sb.ToString();

            if (string.IsNullOrEmpty(result))
                return "Unknown";

            if (char.IsDigit(result[0]))
            {
                result = "_" + result;
            }

            return result;
        }
    }
}